name: Validate Package

on:
  workflow_run:
    workflows: ["Docker"]  # Name of your existing workflow
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and inspect image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest
          docker inspect ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest

      - name: Validate image content
        run: |
          docker create --name temp_container ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest
          docker cp temp_container:/app/requirements.txt ./pulled_requirements.txt
          if cmp -s "./requirements.txt" "./pulled_requirements.txt"; then
            echo "Requirements file matches"
          else
            echo "Requirements file doesn't match"
            exit 1
          fi
          docker rm temp_container

      - name: Run container and test
        run: |
          docker run --name test_container -d ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest
          sleep 10  # Give the container time to start up
          if docker ps | grep -q test_container; then
            echo "Container is running"
          else
            echo "Container failed to start"
            exit 1
          fi
          docker logs test_container
          docker stop test_container
          docker rm test_container