name: Docker

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2
       
       - name: Build the Docker image
         run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest
       
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GHCR_TOKEN }}
       
       - name: Push image to GitHub Container Registry
         run: docker push ghcr.io/${{ github.repository_owner }}/raspberry-pi-2-w-time-machine-radio:latest